# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIFARanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('country_full', models.CharField(max_length=16)),
                ('country_abrv', models.CharField(max_length=16)),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=16)),
                ('previous_points', models.IntegerField()),
                ('rank_change', models.IntegerField()),
                ('cur_year_avg', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cur_year_avg_weighted', models.DecimalField(decimal_places=2, max_digits=16)),
                ('last_year_avg', models.DecimalField(decimal_places=2, max_digits=16)),
                ('last_year_avg_weighted', models.DecimalField(decimal_places=2, max_digits=16)),
                ('two_year_ago_avg', models.DecimalField(decimal_places=2, max_digits=16)),
                ('two_year_ago_weighted', models.DecimalField(decimal_places=2, max_digits=16)),
                ('three_year_ago_avg', models.DecimalField(decimal_places=2, max_digits=16)),
                ('three_year_ago_weighted', models.DecimalField(decimal_places=2, max_digits=16)),
                ('confederation', models.CharField(max_length=16)),
                ('rank_date', models.DateField()),
            ],
        ),
    ]
