# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-20 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0002_auto_20180920_1113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fifaranking',
            table='fifa_ranking',
        ),
    ]
