# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdata', '0003_auto_20180920_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifaranking',
            name='country_full',
            field=models.CharField(max_length=64),
        ),
    ]
